name: Stay Hungry, Stay Foolish
url:  "http://xericzephyr.github.io/blog/"
description: Zheng Xu's Dark Cell
meta_description: "Stay Hungry, Stay Foolish, Zheng Xu's Dark Cell"
paginate: 15

markdown: redcarpet
redcarpet:
    extensions: [with_toc_data]
highlighter: pygments
logo: false