name: Stay Hungry, Stay Foolish
url:  "http://xuzheng.pw/blog/"
description: Zheng Xu's Dark Cell
meta_description: "Stay Hungry, Stay Foolish, Zheng Xu's Dark Cell"


markdown: redcarpet
redcarpet:
    extensions: [with_toc_data]
highlighter: pygments
logo: false

baseurl: /blog

relative_permalinks: true
permalink: /:year/:month/:day/:title
paginate_path: /page/:num
paginate: 15
